FROM ghcr.io/jiotv-go/jiotv_go

# Enforce correct time zones and video streaming layers
ENV TZ=Asia/Kolkata
ENV JIOTV_DRM=true

# Force the binary to bypass local network limits and serve on Vercel's port 80
CMD ["serve", "--public", "--port", "80"]
